---
title: "week1-Quiz"
author: "Kevin Ho"
date: "8 December 2016"
output: html_document
---

```{r knitr setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)



```

```{r setvariables}
dataLoc <- "C:/Users/kxho/Documents/R-Dev/Capstone/data"
```

```{r loadpackages}
require(stringr)

```


```{r loaddata, cache=TRUE}
twitter <- readLines(paste(file=dataLoc,"/en_US.twitter.txt",sep=""))
blogs <- readLines(paste(file=dataLoc,"/en_US.blogs.txt",sep=""))
news  <- readLines(paste(file=dataLoc,"/en_US.news.txt",sep=""))
```

#Question 1
```{r}
file.size(paste(dataLoc,"/en_US.blogs.txt",sep=""))
```

#Question 2
```{r}
length(twitter)
```

#Question 3
```{r}
max(apply(data.frame(twitter),1,str_length))
max(apply(data.frame(news),1,str_length))
max(apply(data.frame(blogs),1,str_length))
```

#Question 4
```{r}
length(grep("love",twitter))/length(grep("hate",twitter))
```

#Question 5
```{r}
twitter[grep("biost",twitter)]
```

#Question 6
```{r}
length(twitter[grep("A computer once beat me at chess, but it was no match for me at kickboxing",twitter)])
```

#System Info
##Version
```{r sysinfo}
R.version

Sys.info()
```

##Installed Packages
```{r installedpackages, echo = FALSE}
ip <- as.data.frame(installed.packages()[,c(1,3:4)])
rownames(ip) <- NULL
ip <- ip[is.na(ip$Priority),1:2,drop = FALSE]
print(ip, row.names=FALSE)
```